// Centralized image path exports to avoid inline long lists in components

export const VTR_IMAGES = {
  himalayasView: "/images/vtr images/Himalaya's view.jpg",
  jungleAnimals: "/images/vtr images/jungle animals.jpg",
  jungleSafari: "/images/vtr images/jungle safari.jpg",
  png2pdf01: "/images/vtr images/png2pdf (1)_merged-01.jpg",
  png2pdf02: "/images/vtr images/png2pdf (1)_merged-02.jpg",
  png2pdf03: "/images/vtr images/png2pdf (1)_merged-03.jpg",
  png2pdf04: "/images/vtr images/png2pdf (1)_merged-04.jpg",
  png2pdf05: "/images/vtr images/png2pdf (1)_merged-05.jpg",
  png2pdf06: "/images/vtr images/png2pdf (1)_merged-06.jpg",
  png2pdf07: "/images/vtr images/png2pdf (1)_merged-07.jpg",
  png2pdf08: "/images/vtr images/png2pdf (1)_merged-08.jpg",
  png2pdf09: "/images/vtr images/png2pdf (1)_merged-09.jpg",
  png2pdf10: "/images/vtr images/png2pdf (1)_merged-10.jpg",
  png2pdf11: "/images/vtr images/png2pdf (1)_merged-11.jpg",
  png2pdf12: "/images/vtr images/png2pdf (1)_merged-12.jpg",
  png2pdf13: "/images/vtr images/png2pdf (1)_merged-13.jpg",
  png2pdf14: "/images/vtr images/png2pdf (1)_merged-14.jpg",
  png2pdf15: "/images/vtr images/png2pdf (1)_merged-15.jpg",
  png2pdf16: "/images/vtr images/png2pdf (1)_merged-16.jpg",
  png2pdf17: "/images/vtr images/png2pdf (1)_merged-17.jpg",
  png2pdf18: "/images/vtr images/png2pdf (1)_merged-18.jpg",
  png2pdf19: "/images/vtr images/png2pdf (1)_merged-19.jpg",
  png2pdf20: "/images/vtr images/png2pdf (1)_merged-20.jpg",
  png2pdf21: "/images/vtr images/png2pdf (1)_merged-21.jpg",
  png2pdf22: "/images/vtr images/png2pdf (1)_merged-22.jpg",
  png2pdf23: "/images/vtr images/png2pdf (1)_merged-23.jpg",
  png2pdf24: "/images/vtr images/png2pdf (1)_merged-24.jpg",
  png2pdf25: "/images/vtr images/png2pdf (1)_merged-25.jpg",
  png2pdf26: "/images/vtr images/png2pdf (1)_merged-26.jpg",
  png2pdf27: "/images/vtr images/png2pdf (1)_merged-27.jpg",
  png2pdf28: "/images/vtr images/png2pdf (1)_merged-28.jpg",
  png2pdf29: "/images/vtr images/png2pdf (1)_merged-29.jpg",
  png2pdf30: "/images/vtr images/png2pdf (1)_merged-30.jpg",
  png2pdf31: "/images/vtr images/png2pdf (1)_merged-31.jpg",
  png2pdf32: "/images/vtr images/png2pdf (1)_merged-32.jpg",
  png2pdf33: "/images/vtr images/png2pdf (1)_merged-33.jpg",
  png2pdf34: "/images/vtr images/png2pdf (1)_merged-34.jpg",
  png2pdf35: "/images/vtr images/png2pdf (1)_merged-35.jpg",
  png2pdf36: "/images/vtr images/png2pdf (1)_merged-36.jpg",
  png2pdf37: "/images/vtr images/png2pdf (1)_merged-37.jpg",
  png2pdf38: "/images/vtr images/png2pdf (1)_merged-38.jpg",
  png2pdf39: "/images/vtr images/png2pdf (1)_merged-39.jpg",
  png2pdf40: "/images/vtr images/png2pdf (1)_merged-40.jpg",
  png2pdf41: "/images/vtr images/png2pdf (1)_merged-41.jpg",
  png2pdf42: "/images/vtr images/png2pdf (1)_merged-42.jpg",
  png2pdf43: "/images/vtr images/png2pdf (1)_merged-43.jpg",
  png2pdf44: "/images/vtr images/png2pdf (1)_merged-44.jpg",
  png2pdf45: "/images/vtr images/png2pdf (1)_merged-45.jpg",
  png2pdf46: "/images/vtr images/png2pdf (1)_merged-46.jpg",
  png2pdf47: "/images/vtr images/png2pdf (1)_merged-47.jpg",
  png2pdf48: "/images/vtr images/png2pdf (1)_merged-48.jpg",
  png2pdf49: "/images/vtr images/png2pdf (1)_merged-49.jpg",
  png2pdf50: "/images/vtr images/png2pdf (1)_merged-50.jpg",
  png2pdf51: "/images/vtr images/png2pdf (1)_merged-51.jpg",
  png2pdf52: "/images/vtr images/png2pdf (1)_merged-52.jpg",
  png2pdf53: "/images/vtr images/png2pdf (1)_merged-53.jpg",
  png2pdf54: "/images/vtr images/png2pdf (1)_merged-54.jpg",
  png2pdf57: "/images/vtr images/png2pdf (1)_merged-57.jpg",
  png2pdf58: "/images/vtr images/png2pdf (1)_merged-58.jpg",
  png2pdf61: "/images/vtr images/png2pdf (1)_merged-61.jpg",
  png2pdf62: "/images/vtr images/png2pdf (1)_merged-62.jpg",
  safari1: "/images/vtr images/safari 1.jpg",
  river1: "/images/vtr images/river 1.jpg",
  vtr1: "/images/vtr images/vtr 1.jpg",
  valmikiAsshram: "/images/vtr images/valmiki asshram.jpg",
  boating: "/images/vtr images/boating.jpg",
  denseForest: "/images/vtr images/dense forest.jpg",
  hangingBridge: "/images/vtr images/Hanging bridge.jpg",
  nardeviMandir: "/images/vtr images/Nardevi Maa Mandir.jpg",
  valmikinagarSunset: "/images/vtr images/valmikinagar sunset.jpg",
  safari: "/images/vtr images/safari.jpg",
  tiger: "/images/vtr images/tiger.jpg",
  hiking: "/images/vtr images/hiking.jpg",
};
